---
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
---
  spring:
    profiles: cloud-service1
  words: I,You,He,She,It
---
  spring:
    profiles: cloud-service2
  words: ran,knew,had,saw,bought
---
  spring:
    profiles: cloud-service3
  words: a,the
---
  spring:
    profiles: cloud-service4
  words: reasonable,leaky,suspicious,ordinary,unlikely
---
  spring:
    profiles: cloud-service7
  words: boat,book,vote,seat,backpack,partition,groundhog
